# frozen_string_literal: true

source "https://rubygems.org"

gem "puma"
gem "rack"
gem "syro"

group :development do
  gem "pry"
  gem "rt_rubocop_defaults", require: false
  gem "rubocop_runner", "~> 2.1", require: false
  gem "shotgun"
end

group :test do
  gem "factory_bot"
  gem "faker"
  gem "rack-test"
  gem "rspec"
end
