---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unleash
  labels:
    app: unleash
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: unleash
  template:
    metadata:
      labels:
        app: unleash
        deployment: unleash
        app.kubernetes.io/name: {{ .Values.keptn.service }}
        app.kubernetes.io/instance: "{{ .Values.keptn.service }}-{{ .Values.keptn.deployment }}"
        app.kubernetes.io/component: unleash
        app.kubernetes.io/part-of: "{{ .Values.keptn.project }}"
        app.kubernetes.io/managed-by: Keptn
        app.kubernetes.io/version: {{ (split ":" .Values.image)._1 | default "latest" }}         
    spec:
      containers:
      - name: unleash
        image: {{ .Values.image }}
        imagePullPolicy: Always
        ports:
        - containerPort: 4242
        env:
        - name: NODE_ENV
          value: 'production'
        - name: DATABASE_URL
          value: postgres://postgres:somepassword@unleash-db/db
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
