---
apiVersion: v1
kind: Service
metadata:
  name: unleash
  annotations:
    service.alpha.kubernetes.io/app-protocols: '{"http-port":"HTTP"}'
  labels:
    app: unleash
spec:
  type: NodePort
  selector:
    app: unleash
  ports:
  - name: http-port
    port: 80
    targetPort: 4242