---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: carts-db-mongodata
  namespace: sockshop-hardening
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: carts-db
  namespace: sockshop-hardening
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carts-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: carts-db
    spec:
      containers:
      - image: mongo
        name: carts-db
        ports:
        - containerPort: 27017
        resources: {}
        volumeMounts:
        - mountPath: /data/db
          name: carts-db-mongodata
      restartPolicy: Always
      volumes:
      - name: carts-db-mongodata
        persistentVolumeClaim:
          claimName: carts-db-mongodata
---
apiVersion: v1
kind: Service
metadata:
  name: carts-db
  namespace: sockshop-hardening
spec:
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
  selector:
    app: carts-db
